<a href="https://colab.research.google.com/github/MariaKausar/AI-Based-Manufacturing-Cost-Prediction-Dashboard-System/blob/main/AI_Manufacturing_Cost_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Dataset Creation**

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

# Number of samples
n = 200

data = {
    "material_cost": np.random.randint(50, 500, n),
    "labour_hours": np.random.randint(1, 20, n),
    "machine_time": np.random.randint(1, 10, n),
    "quantity": np.random.randint(1, 100, n),
}

df = pd.DataFrame(data)

# Simple formula to create target (Total Cost)
df["total_cost"] = (
    df["material_cost"] * df["quantity"] +
    df["labour_hours"] * 20 +
    df["machine_time"] * 50
)

df.head()

   material_cost  labour_hours  machine_time  quantity  total_cost
0            152            12             4        28        4696
1            485            11             2         8        4200
2            398             7             3        92       36906
3            320             1             1        36       11590
4            156             1             8        90       14460

In [2]:
#Dateset save and describe
df.to_csv("manufacturing_data.csv", index=False)
df.describe()

       material_cost  labour_hours  machine_time    quantity    total_cost
count      200.00000    200.000000    200.000000  200.000000    200.000000
mean       270.27500      9.185000      4.875000   51.260000  14268.270000
std        129.74141      5.889329      2.573419   29.088539  11211.821333
min         51.00000      1.000000      1.000000    1.000000    404.000000
25%        152.00000      3.750000      3.000000   27.000000   5234.500000
50%        269.00000      8.000000      5.000000   51.500000  10705.000000
75%        381.75000     15.000000      7.000000   77.000000  21218.500000
max        498.00000     19.000000      9.000000   99.000000  47670.000000

**AI MODEL that will Predict Cost**

In [3]:
#Dataset Load
df = pd.read_csv("manufacturing_data.csv")
df.head()

   material_cost  labour_hours  machine_time  quantity  total_cost
0            152            12             4        28        4696
1            485            11             2         8        4200
2            398             7             3        92       36906
3            320             1             1        36       11590
4            156             1             8        90       14460

In [4]:
#Features & Target define
X = df[["material_cost", "labour_hours", "machine_time", "quantity"]]
y = df["total_cost"]

In [5]:
#Train model (Linear Regression)
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [6]:
#Model Evalution
from sklearn.metrics import r2_score

y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))

R2 Score: 0.8743138934120332

**AI COST PREDICTOR, Live Input**

In [7]:
import pandas as pd

def predict_cost(material_cost, labour_hours, machine_time, quantity):
    input_data = pd.DataFrame([{
        "material_cost": material_cost,
        "labour_hours": labour_hours,
        "machine_time": machine_time,
        "quantity": quantity
    }])

    prediction = model.predict(input_data)
    return max(0, prediction[0])  # cost negative na ho

In [8]:
predict_cost(200, 5, 3, 10)

0

**Streamlit AI Web app**

In [19]:
!streamlit run app.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.124.165.18:8501

  Stopping...

In [14]:
!pip install pyngrok

Collecting pyngrok
  Downloading pyngrok-8.0.0-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Downloading pyngrok-8.0.0-py3-none-any.whl (24 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.0.0

In [17]:
from pyngrok import ngrok

ngrok.set_auth_token("3CMvHbED1zl2cyty0fAPrqjRbbn_34R9DnuNbG9oQr6eh1Gvr")

In [18]:
public_url = ngrok.connect(8501)
print("Your app is live here:", public_url)

!streamlit run app.py

Your app is live here: NgrokTunnel: "https://scouting-demeaning-duh.ngrok-free.dev" -> "http://localhost:8501"

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.124.165.18:8501

  Stopping...
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 399, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 379, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/bootstrap.py", line 43, in signal_handler
    server.stop()
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/server/server.py", line 544, in stop
    cli_util.print_to_cli("  Stopping...", fg="blue")
  File "/usr/local/lib/python3.12/dist-packages/streamlit/cli_util.py", line 34, in print_to_cli
    click.secho(message, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/click/termui.py", line 690, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/utils.py", line 321, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/bootstrap.py", line 43, in signal_handler
    server.stop()
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/server/server.py", line 544, in stop
    cli_util.print_to_cli("  Stopping...", fg="blue")
  File "/usr/local/lib/python3.12/dist-packages/streamlit/cli_util.py", line 34, in print_to_cli
    click.secho(message, **kwargs)
  File "/usr/local/lib/python3.12/dist-packages/click/termui.py", line 690, in secho
    return echo(message, file=file, nl=nl, err=err, color=color)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/utils.py", line 321, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>
  Stopping...
  Stopping...
Exception ignored in: <module 'threading' from '/usr/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1594, in _shutdown
    atexit_call()
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.12/threading.py", line 1149, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.12/threading.py", line 1169, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/bootstrap.py", line 43, in signal_handler
    server.stop()
  File "/usr/local/lib/python3.12/dist-packages/streamlit/web/server/server.py", line 550, in stop
    self._runtime.stop()
  File "/usr/local/lib/python3.12/dist-packages/streamlit/runtime/runtime.py", line 351, in stop
    async_objs.eventloop.call_soon_threadsafe(stop_on_eventloop)
  File "uvloop/loop.pyx", line 1290, in uvloop.loop.Loop.call_soon_threadsafe
  File "uvloop/loop.pyx", line 673, in uvloop.loop.Loop._append_ready_handle
  File "uvloop/loop.pyx", line 705, in uvloop.loop.Loop._check_closed
RuntimeError: Event loop is closed